### ISSUE TITLE
Does not support users with non-trivial IPv6 address.

### ISSUE THREAD

**Issue by mythmon** [django-pci/django-axes#88]
Since IPv6 address are often longer than IPv4 address, the database storage for the IP address gets truncated, causing failures when a user tries to log in.

I believe that one way to solve this is to use a [`GenericIPAddressField`][0], which supports longer IP addresses, like IPv6.

This would, unfortunately, mean a database change, and I notice that Axes doesn't have any migration set up yet (such as South). I'm not sure what the migration strategy for this would be.

[0]: https://docs.djangoproject.com/en/dev/ref/models/fields/#genericipaddressfield

**Comment by aclysma** [comment]
This is still broken because is_valid_ip() will fail for ipv6 since it's just using socket.inet_aton. BTW using socket.inet_aton directly will also fail to detect bad IP addresses like "127.0"

I would suggest using the built-in django validators (assuming they exist in the versions of django you want to target). I have done this in my fork, so you could easily lift it from there:
https://github.com/aclysma/django-axes/commit/ae52351561aeffcf1a5d4f8a6a06239f81c197f0

As an aside, that commit also removes the IP sanitization. In my opinion it's much better to let people do that for themselves in middleware for reasons mentioned here: http://django-ratelimit.readthedocs.org/en/latest/security.html#security-chapter

**Comment by camilonova** [comment]
@aclysma Can you do a PR with those changes?

**Comment by aclysma** [comment]
Per your request, I sent a pull request, but it includes all my changes, several of which are very opinionated.. you probably **don't** want to take some of them. It may be easier/safer to just lift the ip address validation code manually.

**Comment by aclysma** [comment]
FYI the failed test test_log_data_truncated is failing because I removed storing GET/POST params (this is one of those opinionated changes that you likely don't want to take.)

**Comment by camilonova** [comment]
@aclysma Looks great. Can you please send the PR only with the ip validation changes?

**Comment by camilonova** [comment]
This should be fixed by now
