### ISSUE TITLE
Not sending lockout signal

### ISSUE THREAD

**Issue by zoten** [django-pci/django-axes#94]
The library doesn't send the lockout signal. Tried both with decorator and middleware.
Debugging check_request, it does not pass through it when locking out the user, maybe the control
```python
if is_already_locked(request):
```
in watch_login prevents the signal sending by returning directly?
Or am I missing something else?

**Comment by vlanard** [comment]
+1 for this issue - code never hits the signal send line because of the check above and the fact that
failures > FAILURE_LIMIT 
is never True because failures gets capped at 5 (before is_already_locked() prevents reaching this line a 2nd time), and FAILURE_LIMIT = 5. 

it would be really nice to have access to this lockout signal to be able to customize site behavior at the point of user lockout (e.g. notify admin or record suspicious activity).

**Comment by aclark4life** [comment]
@zoten Where is your PR? I don't see it.

**Comment by zoten** [comment]
@aclark4life I think it has been rejected because it seemed to break some tests, which I hadn't the time to fix.
You can still find the one-line-diff at
https://github.com/zoten/django-axes/commit/f3f93712867c8d175d8494c91823b5a197a8649f

**Comment by toabi** [comment]
Jep, this issue would also be important for me.

**Comment by zoten** [comment]
Great job!

**Comment by sergiolepore** [comment]
@zoten thanks for fixing this weird bug!
@aclark4life are you going to release a new version soon? Thanks!

**Comment by aclark4life** [comment]
Done! https://pypi.python.org/pypi/django-axes/1.4.0

**Comment by sergiolepore** [comment]
@aclark4life thank you sooo much! :smile:
